# Generated by Django 4.1.1 on 2022-10-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=150)),
                ('finchcall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main_app.finchcoll')),
            ],
        ),
    ]
